### ISSUE TITLE
Can not testing pre-trained model on Cityscape

### ISSUE THREAD

**Issue by Timo-hab** [golnazghiasi/LRR#1]
Hi, i am trying to test the pretrained model on Cityscapes, but get no output.

I downloaded the gtFine_trainvaltest.zip" and "leftImg8bit_trainvaltest.zip', unziped it and saved it in /data/CityScapes/.
So the paths are: 
/data/CityScapes/gtFine/val/frankfurt/...
/data/CityScapes/leftImg8bit/val/frankfurt/...

But when i execute, it says: Number of validation data: 0

The output of imdb is the following: 

```
   `root_path: 'data/CityScapes/'
    anno_path: 'data/CityScapes//%s/%s/%s/%s'
     img_path: 'data/CityScapes//leftImg8bit/%s/%s/%s_leftImg8bit.png'
         sets: [1x1 struct]
      classes: [1x1 struct]
       images: [1x1 struct]
  num_classes: 19
classes_names: {1x19 cell}`
```

Maybe the two "//" in the path cause the problem?

**Comment by golnazghiasi** [comment]
The default path to data (opts.dataDir) in "LRRTestOnCityScape.m" is "data/CityScapes/"  which is a local directory. If you have saved your data in "/data/CityScapes/" then you should change "opts.dataDir" to "/data/CityScapes/".
